name: personal-brain
version: 1.1.0
description: TheBrain MCP Server - FastMCP Python implementation

# No workdir needed - we're already in the python directory
# Installation command
install: pip install -e .

# Command to run the server
command: python -m thebrain_mcp.server

# Environment variables (these should be set in FastMCP Cloud UI)
environment:
  THEBRAIN_API_KEY: ${THEBRAIN_API_KEY}
  THEBRAIN_DEFAULT_BRAIN_ID: ${THEBRAIN_DEFAULT_BRAIN_ID}
  THEBRAIN_VAULT_BRAIN_ID: ${THEBRAIN_VAULT_BRAIN_ID}
  BTCPAY_HOST: ${BTCPAY_HOST}
  BTCPAY_STORE_ID: ${BTCPAY_STORE_ID}
  BTCPAY_API_KEY: ${BTCPAY_API_KEY}
  BTCPAY_TIER_CONFIG: ${BTCPAY_TIER_CONFIG}
  BTCPAY_USER_TIERS: ${BTCPAY_USER_TIERS}
  SEED_BALANCE_SATS: ${SEED_BALANCE_SATS:-1000}

# Python version
runtime:
  python: "3.12"
